### ISSUE TITLE
Unable to connect to datastore with a username.

### ISSUE THREAD

**Issue by accessguru** [launchdarkly/dotnet-server-sdk-redis#29]
We have a Redis datastore that we've been testing with successfully with a password until we introduced the username.  I can confirm that the connection works with the username/password when using the Redis Browser.

![image](https://github.com/launchdarkly/dotnet-server-sdk-redis/assets/7512620/e467fdde-3f27-4ab9-b779-8767c9921a09)

However, when attempting to connect with this .NET code, the following exception occurs.  

```
        private static LdClient GetLaunchDarklyClient()
        {
            const string sdkKey = "sdk-key";

            const string userName =  "someusername";
            const string password = "password";
            const string ipAddress = "10.100.0.4";
            const string port = "6379";

            var config = Configuration.Builder(sdkKey)
                .Logging(Components.Logging().Level(LogLevel.Debug))
                .DataStore(
                    Components.PersistentDataStore(
                        Redis.DataStore()
                            .Uri($"redis://{userName}:{password}@{ipAddress}:{port}")
                            .Prefix("launchdarkly")
                    ).CacheSeconds(30)
                )
                .Build();

            return new LdClient(config);
        }
```

StackExchange.Redis.RedisConnectionException
  HResult=0x80131500
  Message=It was not possible to connect to the redis server(s). There was an authentication failure; check that passwords (or client certificates) are configured correctly. AuthenticationFailure (None, last-recv: 365) on 10.100.0.4:6379/Interactive, Flushed, last: ECHO, origin: SetResult, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 9 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.513.63329
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 943
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 915
   at LaunchDarkly.Sdk.Server.Integrations.RedisStoreImplBase..ctor(ConfigurationOptions redisConfig, String prefix, Logger log)
   at LaunchDarkly.Sdk.Server.Integrations.RedisDataStoreImpl..ctor(ConfigurationOptions redisConfig, String prefix, Logger log)
   at LaunchDarkly.Sdk.Server.Integrations.BuilderForDataStore.Build(LdClientContext context)
   at LaunchDarkly.Sdk.Server.Integrations.PersistentDataStoreBuilder.Build(LdClientContext context)
   at LaunchDarkly.Sdk.Server.LdClient..ctor(Configuration config)
   at LaunchDarklyProxy.Program.GetLaunchDarklyClient() in C:\Users\LawrenceMantin\source\repos\LaunchDarklyProxy\LaunchDarklyProxy\Program.cs:line 97
   at LaunchDarklyProxy.Program.Main(String[] args) in C:\Users\LawrenceMantin\source\repos\LaunchDarklyProxy\LaunchDarklyProxy\Program.cs:line 21

**Comment by tanderson-ld** [comment]
Thank you for reporting this issue.  We will dig a little and let you know what we find.

**Comment by tanderson-ld** [comment]
It appears for some reason that when this library was written, it assumed the username wasn't necessary.  [See this line.](https://github.com/launchdarkly/dotnet-server-sdk-redis/blame/main/src/LaunchDarkly.ServerSdk.Redis/RedisStoreBuilder.cs#L123) .

You might be able to do either of the following to work around it:

1. Invoke [RedisConfigChanges](https://github.com/launchdarkly/dotnet-server-sdk-redis/blame/main/src/LaunchDarkly.ServerSdk.Redis/RedisStoreBuilder.cs#L221) and set the username yourself
2. Pass an entire config object into the builder [here](https://github.com/launchdarkly/dotnet-server-sdk-redis/blame/main/src/LaunchDarkly.ServerSdk.Redis/RedisStoreBuilder.cs#L73).

Let me know if either of those doesn't work.  I think I would go with Option 1 for now.

**Comment by tanderson-ld** [comment]
Also created SC-245495 to track adding username parsing for future ease of use.

**Comment by tanderson-ld** [comment]
Did either of those options work for you?
